### ISSUE TITLE
Implement Q4'19 CAI Resources in Forseti Inventory

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3288]
- [ ] Identify all CAI resources launched in this quarter and add to list below.
- [ ] Break work down as needed into smaller issues to fit into team sprints and add them to this Epic
- [ ] Before closing this issue for the quarter. Open new issue and convert to Epic to track CAI resources for the next quarter.

CAI Content Type | Availability | GitHub Issue | Status
-- | -- | -- | --
serviceusage.services | 2019-10-30 | https://github.com/forseti-security/forseti-security/issues/3391 | Done
k8s.io/Service | (2019-11-13) |  https://github.com/forseti-security/forseti-security/issues/3443 | Done
extensions.k8s.io/Ingress | (2019-11-13) | https://github.com/forseti-security/forseti-security/issues/3444 | Blocked

Implement the following  CAI resources once they are out of beta:

CAI Content Type | Availability | GitHub Issue | Status
-- | -- | -- | --
container.googleapis.com/NodePool | GA TBD |  [#3010](https://github.com/forseti-security/forseti-security/issues/3010) | Planning
