### ISSUE TITLE
Add default interrupts task list to new issues

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3344]
Enable [auto-comment bot](https://probot.github.io/apps/auto-comment/) to automatically add interrupts tasks to new issues.

- [x] add auto comment bot yaml https://github.com/forseti-security/forseti-security/pull/3343
- [x] enable auto comment bot on Forseti Security project
- [x] test bot is working with new comment added to new issues.

**Comment by dekuhn** [comment]
Fixing  configuration value name https://github.com/forseti-security/forseti-security/pull/3395/files

**Comment by dekuhn** [comment]
Fixes https://github.com/forseti-security/forseti-security/issues/3396
