### ISSUE TITLE
Implement Q1'2020 CAI Resources in Forseti Inventory

### ISSUE THREAD

**Issue by dekuhn** [forseti-security/forseti-security#3610]
- [ ] Identify all CAI resources launched in this quarter and add to list below.
- [ ] Break work down as needed into smaller issues to fit into team sprints and add them to this Epic
- [ ] Before closing this issue for the quarter. Open new issue and convert to Epic to track CAI resources for the next quarter.

CAI Content Type | Availability | GitHub Issue
-- | -- | --
networking.k8s.io/Ingress | (2020-01-27) | #3609

**Comment by dekuhn** [comment]
Still blocked due to the networking.k8s.io/Ingress being in Beta.
